source = ./vars.conf
source = ./host-specific.conf

env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 24

exec-once = waybar
exec-once = mako
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

general {
  gaps_in = 2
  gaps_out = 5
  border_size = 2
  col.active_border = rgba($fg80)
  col.inactive_border = rgba($bg00)
  layout = dwindle
}

cursor {
  inactive_timeout = 10
}

misc {
  disable_hyprland_logo = true
  background_color = rgb($bg) 
  font_family = $font
}

input {
  kb_layout = us, de
  kb_options = grp:alt_shift_toggle

  follow_mouse = 1
  sensitivity = 0 

  touchpad {
    natural_scroll = yes
    disable_while_typing = yes
  }
}

gestures {
  workspace_swipe = on
  workspace_swipe_distance = 200
  workspace_swipe_create_new = false
}

animations {
  enabled = yes
  bezier = wind, 0.05, 0.9, 0.1, 1
  bezier = winIn, 0.1, 1, 0.1, 1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = liner, 1, 1, 1, 1
  animation = windows, 1, 6, wind, slide
  animation = windowsIn, 1, 6, winIn, slide
  animation = windowsOut, 1, 5, winOut, slide
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, liner
  animation = borderangle, 1, 30, liner, loop
  animation = fade, 1, 10, default
  animation = workspaces, 1, 5, wind
  animation = specialWorkspace, 1, 5, wind, slidevert
}

source = ./binds.conf
